"""Add facility relationships

Revision ID: 15946de45445
Revises: af09deb5d8dd
Create Date: 2024-10-31 00:34:42.833783

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '15946de45445'
down_revision = 'af09deb5d8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userfacility')
    op.add_column('userassembler', sa.Column('facility_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'userassembler', 'facilitytype', ['facility_type_id'], ['id'])
    op.add_column('userconstructor', sa.Column('facility_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'userconstructor', 'facilitytype', ['facility_type_id'], ['id'])
    op.add_column('userminer', sa.Column('facility_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'userminer', 'facilitytype', ['facility_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userminer', type_='foreignkey')
    op.drop_column('userminer', 'facility_type_id')
    op.drop_constraint(None, 'userconstructor', type_='foreignkey')
    op.drop_column('userconstructor', 'facility_type_id')
    op.drop_constraint(None, 'userassembler', type_='foreignkey')
    op.drop_column('userassembler', 'facility_type_id')
    op.create_table('userfacility',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('facility_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['facility_type_id'], ['facilitytype.id'], name='userfacility_facility_type_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='userfacility_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='userfacility_pkey')
    )
    # ### end Alembic commands ###
