"""change item_type_id fk to facility_type_id fk

Revision ID: 27a97b2aebc6
Revises: 2c7d960c3de4
Create Date: 2024-10-21 05:01:39.268894

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '27a97b2aebc6'
down_revision = '2c7d960c3de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userfacility', sa.Column('facility_type_id', sa.Integer(), nullable=False))
    op.drop_constraint('userfacility_item_type_id_fkey', 'userfacility', type_='foreignkey')
    op.create_foreign_key(None, 'userfacility', 'facilitytype', ['facility_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('userfacility', 'item_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userfacility', sa.Column('item_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'userfacility', type_='foreignkey')
    op.create_foreign_key('userfacility_item_type_id_fkey', 'userfacility', 'facilitytype', ['item_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('userfacility', 'facility_type_id')
    # ### end Alembic commands ###
