"""Add recipes to facilities

Revision ID: 55ccdf31104d
Revises: dd2aa2796c57
Create Date: 2024-11-04 22:41:28.307994

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '55ccdf31104d'
down_revision = 'dd2aa2796c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userassembler', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userassembler', 'recipe', ['recipe_id'], ['id'])
    op.add_column('userconstructor', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userconstructor', 'recipe', ['recipe_id'], ['id'])
    op.add_column('userminer', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userminer', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userminer', type_='foreignkey')
    op.drop_column('userminer', 'recipe_id')
    op.drop_constraint(None, 'userconstructor', type_='foreignkey')
    op.drop_column('userconstructor', 'recipe_id')
    op.drop_constraint(None, 'userassembler', type_='foreignkey')
    op.drop_column('userassembler', 'recipe_id')
    # ### end Alembic commands ###
