"""remove extra recipe columns

Revision ID: dd2aa2796c57
Revises: e9e2ca992fb7
Create Date: 2024-11-04 07:48:57.154832

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd2aa2796c57'
down_revision = 'e9e2ca992fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('userassembler_recipe_id_fkey', 'userassembler', type_='foreignkey')
    op.drop_column('userassembler', 'recipe_id')
    op.drop_constraint('userconstructor_recipe_id_fkey', 'userconstructor', type_='foreignkey')
    op.drop_column('userconstructor', 'recipe_id')
    op.drop_constraint('userminer_recipe_id_fkey', 'userminer', type_='foreignkey')
    op.drop_column('userminer', 'recipe_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userminer', sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('userminer_recipe_id_fkey', 'userminer', 'recipe', ['recipe_id'], ['id'])
    op.add_column('userconstructor', sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('userconstructor_recipe_id_fkey', 'userconstructor', 'recipe', ['recipe_id'], ['id'])
    op.add_column('userassembler', sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('userassembler_recipe_id_fkey', 'userassembler', 'recipe', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
