"""Relate facility_type and recipe

Revision ID: e9e2ca992fb7
Revises: 15946de45445
Create Date: 2024-11-03 21:51:06.736004

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e9e2ca992fb7'
down_revision = '15946de45445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('facility_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'facilitytype', ['facility_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'facility_type_id')
    # ### end Alembic commands ###
